# Generated by Django 4.1.3 on 2022-11-25 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a name', max_length=30)),
                ('surname', models.CharField(help_text='Enter a surname', max_length=30)),
                ('graduateDate', models.DateField(help_text='Enter a date of graduation')),
                ('quote', models.CharField(help_text='Enter a quote of student', max_length=200)),
            ],
        ),
    ]
